-- INSERT CLINICA
INSERT INTO CLINICA VALUES (1, 'The Way','http://www.clinicatheway.com.br/');

-- INSERT UNIDADE
INSERT INTO UNIDADE VALUES(1,1,'Osasco','','','SP','Osasco','Rua Eloy Candido Lopes, 137 - Centro','06010130');

-- INSERT TRATAMENTO
INSERT INTO TRATAMENTO VALUES (1, 'Alcool');
INSERT INTO TRATAMENTO VALUES (2, 'Drogas');

-- INSERT UNIxTRATAMENTO
INSERT INTO UNIxTRATAMENTO VALUES (1,1);
INSERT INTO UNIxTRATAMENTO VALUES (1,2);

-- INSERT TELEFONE
INSERT INTO TELEFONE VALUES (1,1,'11984161044');
