-- FALTAM AS CLINICAS ANADEQ E TRATAMENTO DROGAS E ALCOOL
-- INSERT CLINICA
INSERT INTO CLINICA VALUES (1, 'The Way','http://www.clinicatheway.com.br/');
INSERT INTO CLINICA VALUES (2, 'Clinicas Master','http://www.clinicasmaster.com.br/');
INSERT INTO CLINICA VALUES (3, 'Clinica De Recuperação Prime','https://www.clinicaparareabilitacao.com.br/');
INSERT INTO CLINICA VALUES (4, 'Anjos de Uma Asa','https://www.anjosdeumaasa.com.br/');
INSERT INTO CLINICA VALUES (5, 'San Paolo','http://clinicassanpaolo.com.br/');
INSERT INTO CLINICA VALUES (6, 'Grupo Recuperar','https://www.gruporecuperar.com/');



-- INSERT UNIDADE
INSERT INTO UNIDADE VALUES(1,1,'Osasco','','','SP','Osasco','Rua Eloy Candido Lopes, 137 - Centro','06010130');
INSERT INTO UNIDADE VALUES(2,1,'Presidente Altino','','','SP','Osasco','Rua Erasmo Braga - Pres. Altino','06213008');
INSERT INTO UNIDADE VALUES(3,1,'Butantã','','','SP','São Paulo','Rodovia Raposo Tavares, 5573 - Butantã','05573900');
INSERT INTO UNIDADE VALUES(4,2,'Jabaquara','','','SP','São Paulo','R. Ten. Alcídes Machado','04349100');
INSERT INTO UNIDADE VALUES(5,2,'Cotia','M','','SP','Cotia','R. Fênix, 358-508 - Chácara Rincão','06721435');
INSERT INTO UNIDADE VALUES(6,3,'Barueri','','','SP','Barueri','Rua Werner Goldberg, 179 - 83 A - Jardim Esperanca','06414025');
INSERT INTO UNIDADE VALUES(7,3,'Alto de Pinheiros','F','','SP','São Paulo','Av. São Gualter - Alto de Pinheiros','03178200');
INSERT INTO UNIDADE VALUES(8,3,'Pinheiros','','','SP','São Paulo','Av. das Nações Unidas, 145 - Pinheiros','03178200');
INSERT INTO UNIDADE VALUES(9,3,'Itapecerica da Serra','','','SP','Itapecerica da Serra','Av. dos Itapecericanos - Parque Paraiso','06850135');
INSERT INTO UNIDADE VALUES(10,4,'Cajamar','M','','SP','Cajamar','R. Pedra Bela - Ponunduva','07750000');
INSERT INTO UNIDADE VALUES(11,5,'Osasco','','','SP','Osasco','Rua Cisne - Aliança','06236730');
INSERT INTO UNIDADE VALUES(12,5,'Higienópolis','','','SP','São Paulo','R. Pernambuco, 109 - 101 - Higienópolis','01240020');
INSERT INTO UNIDADE VALUES(13,6,'Cotia','M','','SP','Cotia','R. Gerônimo de Albuquerque, 534 - Jardim Japao (Caucaia do Alto)','06726120');
INSERT INTO UNIDADE VALUES(14,6,'Vila Mariana','','','SP','São Paulo','R. Cubatão, 674 - Vila Mariana','04013003');
INSERT INTO UNIDADE VALUES(15,6,'Morumbi','','','SP','São Paulo','R. nicolla rollo , 23 - apt. 63A - Morumbi','05726140');

-- INSERT TRATAMENTO
INSERT INTO TRATAMENTO VALUES (1, 'Alcool');
INSERT INTO TRATAMENTO VALUES (2, 'Drogas');

-- INSERT UNIxTRATAMENTO
INSERT INTO UNIxTRATAMENTO VALUES (1,1);
INSERT INTO UNIxTRATAMENTO VALUES (1,2);
INSERT INTO UNIxTRATAMENTO VALUES (2,1);
INSERT INTO UNIxTRATAMENTO VALUES (2,2);
INSERT INTO UNIxTRATAMENTO VALUES (3,1);
INSERT INTO UNIxTRATAMENTO VALUES (3,2);
INSERT INTO UNIxTRATAMENTO VALUES (4,1);
INSERT INTO UNIxTRATAMENTO VALUES (4,2);
INSERT INTO UNIxTRATAMENTO VALUES (5,1);
INSERT INTO UNIxTRATAMENTO VALUES (5,2);
INSERT INTO UNIxTRATAMENTO VALUES (6,1);
INSERT INTO UNIxTRATAMENTO VALUES (6,2);
INSERT INTO UNIxTRATAMENTO VALUES (7,1);
INSERT INTO UNIxTRATAMENTO VALUES (7,2);
INSERT INTO UNIxTRATAMENTO VALUES (8,1);
INSERT INTO UNIxTRATAMENTO VALUES (9,1);
INSERT INTO UNIxTRATAMENTO VALUES (9,2);
INSERT INTO UNIxTRATAMENTO VALUES (10,1);
INSERT INTO UNIxTRATAMENTO VALUES (10,2);
INSERT INTO UNIxTRATAMENTO VALUES (11,1);
INSERT INTO UNIxTRATAMENTO VALUES (11,2);
INSERT INTO UNIxTRATAMENTO VALUES (12,1);
INSERT INTO UNIxTRATAMENTO VALUES (12,2);
INSERT INTO UNIxTRATAMENTO VALUES (13,1);
INSERT INTO UNIxTRATAMENTO VALUES (13,2);
INSERT INTO UNIxTRATAMENTO VALUES (14,1);
INSERT INTO UNIxTRATAMENTO VALUES (14,2);
INSERT INTO UNIxTRATAMENTO VALUES (15,1);
INSERT INTO UNIxTRATAMENTO VALUES (15,2);

-- INSERT TELEFONE
INSERT INTO TELEFONE VALUES (1,1,'11984161044');
INSERT INTO TELEFONE VALUES (2,2,'11984161044');
INSERT INTO TELEFONE VALUES (3,3,'11984161044');
INSERT INTO TELEFONE VALUES (4,4,'1141585406');
INSERT INTO TELEFONE VALUES (5,5,'1141585406');
INSERT INTO TELEFONE VALUES (6,6,'11947976909');
INSERT INTO TELEFONE VALUES (7,7,'11947976909');
INSERT INTO TELEFONE VALUES (8,8,'11964766410');
INSERT INTO TELEFONE VALUES (9,9,'11947976909');
INSERT INTO TELEFONE VALUES (10,10,'1144070330');
INSERT INTO TELEFONE VALUES (11,11,'11984161044');
INSERT INTO TELEFONE VALUES (12,12,'11984161044');
INSERT INTO TELEFONE VALUES (13,13,'1146115166');
INSERT INTO TELEFONE VALUES (14,14,'1146115166');
INSERT INTO TELEFONE VALUES (15,15,'1146115166');

/*EXEMPLOS INSERT AVALIACAO
INSERT INTO AVALIACAO VALUES (1,1,'Gostei muito, deixei de ser ze droguinha',5,true);
INSERT INTO AVALIACAO VALUES (2,1,'Espaço muito bom, moraria para sempre, acho que voltarei pras drogas',5,true);
INSERT INTO AVALIACAO VALUES (3,1,'Meu filho voltou mais drogado ainda',2,false);
*/